// eslint.config.js
const tsParser = require("@typescript-eslint/parser");
const ts = require("@typescript-eslint/eslint-plugin");
const angular = require("@angular-eslint/eslint-plugin");
const path = require("path");

module.exports = [
  // TypeScript files
  {
    // files: ["**/*.ts"],
    // languageOptions: {
    //   parser: tsParser,
    //   parserOptions: {
    //     project: path.resolve(process.cwd(), "tsconfig.json"),
    //     tsconfigRootDir: process.cwd(),
    //   },
    // },

    
  files: ["**/*.ts"],
  languageOptions: {
    parser: tsParser,
    parserOptions: {
      project: [
        path.resolve(__dirname, "tsconfig.app.json"),
        path.resolve(__dirname, "tsconfig.spec.json"),
      ],
      tsconfigRootDir: __dirname,
    },
  },
     
    plugins: {
      "@typescript-eslint": ts,
      "@angular-eslint": angular,
    },
    rules: {
       // Enforce cyclomatic complexity
       "complexity": ["error", { "max": 10 }],

       // Problems (must-have)
       "array-callback-return": "warn",
      "constructor-super": "warn",
      "for-direction": "warn",
      "getter-return": "warn",
      "no-async-promise-executor": "warn",
      "no-await-in-loop": "warn",
      "no-class-assign": "warn",
      "no-compare-neg-zero": "warn",
      "no-cond-assign": "warn",
      "no-const-assign": "warn",
      "no-constant-binary-expression": "warn",
      "no-constant-condition": "warn",
      "no-constructor-return": "warn",
      "no-control-regex": "warn",
      "no-debugger": "warn",
      "no-dupe-args": "warn",
      "no-dupe-class-members": "warn",
      "no-dupe-else-if": "warn",
      "no-dupe-keys": "warn",
      "no-duplicate-case": "warn",
      "no-duplicate-imports": "warn",
      "no-empty-character-class": "warn",
      "no-empty-pattern": "warn",
      "no-ex-assign": "warn",
      "no-fallthrough": "warn",
      "no-func-assign": "warn",
      "no-import-assign": "warn",
      "no-inner-declarations": "warn",
      "no-invalid-regexp": "warn",
      "no-irregular-whitespace": "warn",
      "no-loss-of-precision": "warn",
      "no-misleading-character-class": "warn",
      "no-new-native-nonconstructor": "warn",
      "no-obj-calls": "warn",
      "no-promise-executor-return": "warn",
      "no-prototype-builtins": "warn",
      "no-self-assign": "warn",
      "no-self-compare": "warn",
      "no-setter-return": "warn",
      "no-sparse-arrays": "warn",
      "no-template-curly-in-string": "warn",
      "no-this-before-super": "warn",
      "no-unassigned-vars": "warn",
      "no-undef": "warn",
      "no-unexpected-multiline": "warn",
      "no-unmodified-loop-condition": "warn",
      "no-unreachable": "warn",
      "no-unreachable-loop": "warn",
      "no-unsafe-finally": "warn",
      "no-unsafe-negation": "warn",
      "no-unsafe-optional-chaining": "warn",
      "no-unused-private-class-members": "warn",
      "no-unused-vars": "warn",
      "no-use-before-define": "warn",
      "no-useless-assignment": "warn",
      "no-useless-backreference": "warn",
      "require-atomic-updates": "warn",
      "use-isnan": "warn",
      "valid-typeof": "warn",


       // Suggestions (good-to-have)
       "accessor-pairs": "warn",
      "arrow-body-style": "warn",
      "block-scoped-var": "warn",
      "camelcase": "warn",
      "capitalized-comments": "warn",
      "class-methods-use-this": "warn",
      "complexity": "warn",
      "consistent-return": "warn",
      "consistent-this": "warn",
      "curly": "warn",
      "default-case": "warn",
      "default-case-last": "warn",
      "default-param-last": "warn",
      "dot-notation": "warn",
      "eqeqeq": "warn",
      "func-name-matching": "warn",
      "func-names": "warn",
      "func-style": "warn",
      "grouped-accessor-pairs": "warn",
      "guard-for-in": "warn",
      "id-denylist": "warn",
      "id-length": "warn",
      "id-match": "warn",
      "init-declarations": "warn",
      "logical-assignment-operators": "warn",
      "max-classes-per-file": "warn",
      "max-depth": "warn",
      "max-lines": "warn",
      "max-lines-per-function": "warn",
      "max-nested-callbacks": "warn",
      "max-params": "warn",
      "max-statements": "warn",
      "new-cap": "warn",
      "no-alert": "warn",
      "no-array-constructor": "warn",
      "no-bitwise": "warn",
      "no-caller": "warn",
      "no-case-declarations": "warn",
      "no-console": "warn",
      "no-continue": "warn",
      "no-delete-var": "warn",
      "no-div-regex": "warn",
      "no-else-return": "warn",
      "no-empty": "warn",
      "no-empty-function": "warn",
      "no-empty-static-block": "warn",
      "no-eq-null": "warn",
      "no-eval": "warn",
      "no-extend-native": "warn",
      "no-extra-bind": "warn",
      "no-extra-boolean-cast": "warn",
      "no-extra-label": "warn",
      "no-global-assign": "warn",
      "no-implicit-coercion": "warn",
      "no-implicit-globals": "warn",
      "no-implied-eval": "warn",
      "no-inline-comments": "warn",
      "no-invalid-this": "warn",
      "no-iterator": "warn",
      "no-label-var": "warn",
      "no-labels": "warn",
      "no-lone-blocks": "warn",
      "no-lonely-if": "warn",
      "no-loop-func": "warn",
      "no-magic-numbers": "warn",
      "no-multi-assign": "warn",
      "no-multi-str": "warn",
      "no-negated-condition": "warn",
      "no-nested-ternary": "warn",
      "no-new": "warn",
      "no-new-func": "warn",
      "no-new-wrappers": "warn",
      "no-nonoctal-decimal-escape": "warn",
      "no-object-constructor": "warn",
      "no-octal": "warn",
      "no-octal-escape": "warn",
      "no-param-reassign": "warn",
      "no-plusplus": "warn",
      "no-proto": "warn",
      "no-redeclare": "warn",
      "no-regex-spaces": "warn",
      "no-restricted-exports": "warn",
      "no-restricted-globals": "warn",
      "no-restricted-imports": "warn",
      "no-restricted-properties": "warn",
      "no-restricted-syntax": "warn",
      "no-return-assign": "warn",
      "no-script-url": "warn",
      "no-sequences": "warn",
      "no-shadow": "warn",
      "no-shadow-restricted-names": "warn",
      "no-ternary": "warn",
      "no-throw-literal": "warn",
      "no-undef-init": "warn",
      "no-undefined": "warn",
      "no-underscore-dangle": "warn",
      "no-unneeded-ternary": "warn",
      "no-unused-expressions": "warn",
      "no-unused-labels": "warn",
      "no-useless-call": "warn",
      "no-useless-catch": "warn",
      "no-useless-computed-key": "warn",
      "no-useless-concat": "warn",
      "no-useless-constructor": "warn",
      "no-useless-escape": "warn",
      "no-useless-rename": "warn",
      "no-useless-return": "warn",
      "no-var": "warn",
      "no-void": "warn",
      "no-warning-comments": "warn",
      "no-with": "warn",
      "object-shorthand": "warn",
      "one-var": "warn",
      "operator-assignment": "warn",
      "prefer-arrow-callback": "warn",
      "prefer-const": "warn",
      "prefer-destructuring": "warn",
      "prefer-exponentiation-operator": "warn",
      "prefer-named-capture-group": "warn",
      "prefer-numeric-literals": "warn",
      "prefer-object-has-own": "warn",
      "prefer-object-spread": "warn",
      "prefer-promise-reject-warns": "warn",
      "prefer-regex-literals": "warn",
      "prefer-rest-params": "warn",
      "prefer-spread": "warn",
      "prefer-template": "warn",
      "radix": "warn",
      "require-await": "warn",
      "require-unicode-regexp": "warn",
      "require-yield": "warn",
      "sort-imports": "warn",
      "sort-keys": "warn",
      "sort-vars": "warn",
      "strict": "warn",
      "symbol-description": "warn",
      "vars-on-top": "warn",
      "yoda": "warn",
      "unicode-bom": "warn",
      "array-bracket-newline": "warn",
      "array-bracket-spacing": "warn",
      "array-element-newline": "warn",
      "arrow-parens": "warn",
      "arrow-spacing": "warn",
      "block-spacing": "warn",
      "brace-style": "warn",
      "callback-return": "warn",
      "comma-dangle": "warn",
      "comma-spacing": "warn",
      "comma-style": "warn",
      "computed-property-spacing": "warn",
      "dot-location": "warn",
      "eol-last": "warn",
      "func-call-spacing": "warn",
      "function-call-argument-newline": "warn",
      "function-paren-newline": "warn",
      "generator-star-spacing": "warn",
      "global-require": "warn",
      "handle-callback-err": "warn",
      "id-blacklist": "warn",
      "implicit-arrow-linebreak": "warn",
      "indent": "warn",
      "indent-legacy": "warn",
      "jsx-quotes": "warn",
      "key-spacing": "warn",
      "keyword-spacing": "warn",
      "line-comment-position": "warn",
      "linebreak-style": "warn",
      "lines-around-comment": "warn",
      "lines-around-directive": "warn",
      "lines-between-class-members": "warn",
      "max-len": "warn",
      "max-statements-per-line": "warn",
      "multiline-comment-style": "warn",
      "multiline-ternary": "warn",
      "new-parens": "warn",
      "newline-after-var": "warn",
      "newline-before-return": "warn",
      "newline-per-chained-call": "warn",
      "no-buffer-constructor": "warn",
      "no-catch-shadow": "warn",
      "no-confusing-arrow": "warn",
      "no-extra-parens": "warn",
      "no-extra-semi": "warn",
      "no-floating-decimal": "warn",
      "no-mixed-operators": "warn",
      "no-mixed-requires": "warn",
      "no-mixed-spaces-and-tabs": "warn",
      "no-multi-spaces": "warn",
      "no-multiple-empty-lines": "warn",
      "no-native-reassign": "warn",
      "no-negated-in-lhs": "warn",
      "no-new-object": "warn",
      "no-new-require": "warn",
      "no-new-symbol": "warn",
      "no-path-concat": "warn",
      "no-process-env": "warn",
      "no-process-exit": "warn",
      "no-restricted-modules": "warn",
      "no-return-await": "warn",
      "no-spaced-func": "warn",
      "no-sync": "warn",
      "no-tabs": "warn",
      "no-trailing-spaces": "warn",
      "no-whitespace-before-property": "warn",
      "nonblock-statement-body-position": "warn",
      "object-curly-newline": "warn",
      "object-curly-spacing": "warn",
      "object-property-newline": "warn",
      "one-var-declaration-per-line": "warn",
      "operator-linebreak": "warn",
      "padded-blocks": "warn",
      "padding-line-between-statements": "warn",
      "prefer-reflect": "warn",
      "quote-props": "warn",
      "quotes": "warn",
      "rest-spread-spacing": "warn",
      "semi": "warn",
      "semi-spacing": "warn",
      "semi-style": "warn",
      "space-before-blocks": "warn",
      "space-before-function-paren": "warn",
      "space-in-parens": "warn",
      "space-infix-ops": "warn",
      "space-unary-ops": "warn",
      "spaced-comment": "warn",
      "switch-colon-spacing": "warn",
      "template-curly-spacing": "warn",
      "template-tag-spacing": "warn",
      "wrap-iife": "warn",
      "wrap-regex": "warn",
      "yield-star-spacing": "warn",


    },
  }  
];

